# Generated by Django 3.2.22 on 2023-11-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('HistoricalPrice', 'Price')
    ]
