# Generated by Django 3.2.22 on 2023-11-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20231107_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='datetime',
            new_name='lastvisit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userid',
        ),
    ]
