# Generated by Django 3.2.22 on 2023-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_user_lastsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastsubmission',
            field=models.DateTimeField(null=True),
        ),
    ]
