# Generated by Django 3.2.22 on 2023-11-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_user_lastsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastvisit',
        ),
    ]
