# Generated by Django 3.2.22 on 2023-11-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_remove_user_lastvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodayPrice',
        ),
    ]
