# Generated by Django 3.2.22 on 2023-11-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_delete_todayprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.source')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.symbol')),
            ],
        ),
    ]
